### ISSUE TITLE
ammo.wasm.wasm. URL scheme "file" is not supported.

### ISSUE THREAD

**Issue by xx0618** [enable3d/enable3d-website#46]
Fetch API cannot load file:///F:/lib/ammo.wasm.wasm. URL scheme "file" is not supported.
I want to test locally, but the ammo.wasm.wasm file cannot be loaded, can anyone help me! ?
![微信截图_20201010175625](https://user-images.githubusercontent.com/71865768/95652245-3ae7de80-0b22-11eb-84d8-fc7602ef0efb.png)

**Comment by yandeu** [comment]
You have to serve the examples from a local web server.

Do you have node.js installed?

**Comment by yandeu** [comment]
Once you have node.js installed, type `npm install` and `npm start` in your terminal.

**Comment by xx0618** [comment]
I installed node  and  enable3D, but no start terminal.  I will try. Thanks!

**Comment by xx0618** [comment]
> Once you have node.js installed, type `npm install` and `npm start` in your terminal.

I cannot run npm start. The error message is as follows:
![微信截图_20201012095353](https://user-images.githubusercontent.com/71865768/95697347-05054000-0c71-11eb-8faf-ef4bc010ee25.png)
![微信截图_20201012095451](https://user-images.githubusercontent.com/71865768/95697350-07679a00-0c71-11eb-8ab6-2a7e6f6c6406.png)

**Comment by yandeu** [comment]
Please open your terminal and follow these steps:

```console
# clone the repository
git clone https://github.com/enable3d/enable3d-website.git

# navigate to the enable3d-website directory
cd enable3d-website

# install all dependencies
npm i

# run the examples
npm start
```

**Comment by xx0618** [comment]
> ```
> dependencies
> ```

Unable to install dependencies.
![微信截图_20201012195603](https://user-images.githubusercontent.com/71865768/95744042-52130180-0cc5-11eb-8f87-d612bddb01d5.png)
And my directory is nodejs/node_modules/npm/bin/

**Comment by yandeu** [comment]
Why would you want to install `enable3d/ammo-physics`? 
_And it would be `@enable3d/ammo-physics` btw_

Simply run `npm i `, nothing else.

**Comment by xx0618** [comment]
I also tried Npm i, it was the same error.

**Comment by yandeu** [comment]
Well, I recommend you watch some tutorial on nodejs and npm on youtube.
Maybe this one https://youtu.be/jHDhaSSKmB0

**Comment by xx0618** [comment]
alright, thank you very much. I am a novice and do not understand many things. I will watch this video.

**Comment by xx0618** [comment]
Thanks, you can test it locally, thank you very much for your help!

> Well, I recommend you watch some tutorial on nodejs and npm on youtube.
> Maybe this one https://youtu.be/jHDhaSSKmB0

**Comment by yandeu** [comment]
> Thanks, you can test it locally, thank you very much for your help!

You're welcome :)
