### ISSUE TITLE
The TS project fails to reference enable3d

### ISSUE THREAD

**Issue by shahho** [enable3d/enable3d-website#57]
**Describe the bug**
When I installed enable3d@0.25.1 in NPM, I just used A simple line of code to determine if the code would work.
But it went horribly wrong with the warning
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/5937484/183391537-3bcd46a8-b390-413a-8ebf-43bd86f0acdc.png">

In this file path:'./src/demo.ts'

`
import { Project } from 'enable3d';
console.log(Project)`

<img width="300" alt="image" src="https://user-images.githubusercontent.com/5937484/183388817-3dfe0c7a-b7e8-4d41-a1b4-e41e97c76edb.png">
package.json like this:
`"scripts": {
    "build": "webpack",
    "serve": "webpack-dev-server --config webpack.config.js"
  },
  "dependencies": {
    "enable3d": "^0.25.2",
    "typescript": "^3.9.7"
  },
  "devDependencies": {
    "ts-loader": "^6.2.1",
    "webpack": "^4.41.5",
    "webpack-cli": "^3.3.10",
    "webpack-dev-server": "^3.10.1"
  },`
  
  -------------------------------------------------------
  and webpack.config.js like this:
  
  `
  const path = require('path');
module.exports = {
  entry: {
    demo: './src/demo.ts'
  },
  mode: 'production',
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/
      }
    ]
  },
  resolve: {
    extensions: ['.tsx', '.ts', '.js']
  },
  output: {
    filename: "[name].js", 
    path: path.resolve(__dirname, 'dcp-lib'),
    library: 'x-x',
[git-bug-project.zip](https://github.com/enable3d/enable3d-website/files/9280748/git-bug-project.zip)
    libraryTarget: 'umd',
  },
  devServer: {
    contentBase: path.join(__dirname, ''), 
    compress: true,
    port: 8899
  }
}
`

**Have a question?**
The whole project is very simple, you can download the attachments and run the project with `npm run serve` after installing with `npm i`.

<img width="200" alt="image" src="https://user-images.githubusercontent.com/5937484/183390724-764e7f01-36e1-47e5-942f-b1bc713047eb.png">

https://github.com/enable3d/enable3d-website/files/9280773/git-bug-project.zip

[git-bug-project.zip](https://github.com/enable3d/enable3d-website/files/9280773/git-bug-project.zip)

**Comment by yandeu** [comment]
I guess your webpack config is wrong. Has the TypeScript loader not to be in front of the Babel loader?

**Comment by yandeu** [comment]
See this example
https://github.com/enable3d/threejs-ammojs-webpack-example

**Comment by shahho** [comment]
> See this example https://github.com/enable3d/threejs-ammojs-webpack-example

Thank you. You've solved my problem.
